name: CI-php-8.0

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          php_version: "8.0"
          configuration: phpunit.xml
          php_extensions: xdebug

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3